export function createMusicParts() {
    return [
        {
            name: "Бетховен Людвиг ван",
            song: "Лунная Соната",
            instrument: "Фортепиано",
            format: ".pdf",
            price: "Бесплатно",
        },
        {
            name: "Моцарт Вольфганг Амадей",
            song: "Маленькая ночная серенада",
            instrument: "Скрипка",
            format: ".pdf, .midi",
            price: "Premium или 199 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
        {
            name: "Бетховен Людвиг ван",
            song: "Лунная Соната",
            instrument: "Фортепиано",
            format: ".pdf",
            price: "Бесплатно",
        },
        {
            name: "Моцарт Вольфганг Амадей",
            song: "Маленькая ночная серенада",
            instrument: "Скрипка",
            format: ".pdf, .midi",
            price: "Premium или 199 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
        {
            name: "Бетховен Людвиг ван",
            song: "Лунная Соната",
            instrument: "Фортепиано",
            format: ".pdf",
            price: "Бесплатно",
        },
        {
            name: "Моцарт Вольфганг Амадей",
            song: "Маленькая ночная серенада",
            instrument: "Скрипка",
            format: ".pdf, .midi",
            price: "Premium или 199 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
        {
            name: "Бетховен Людвиг ван",
            song: "Лунная Соната",
            instrument: "Фортепиано",
            format: ".pdf",
            price: "Бесплатно",
        },
        {
            name: "Моцарт Вольфганг Амадей",
            song: "Маленькая ночная серенада",
            instrument: "Скрипка",
            format: ".pdf, .midi",
            price: "Premium или 199 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
        {
            name: "Ирума Yiruma",
            song: "Токката и фуга",
            instrument: "Фортепиано",
            format: ".pdf, .jpg",
            price: "Premium или 99 руб.",
        },
    ];
}
